# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false
dist: trusty

#addons
addons:
  postgresql: "9.4"
  apt:
    packages:
    - libpq-dev

services:
  - postgresql

before_script:
  - psql -c 'create database nycflights;' -U postgres

r:
  - oldrel
  - release
  - devel
os:
- linux
- osx
matrix:
  exclude:
  - os: osx
    r: oldrel
  - os: osx
    r: devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && test $TRAVIS_OS_NAME = "linux" && Rscript -e 'covr::codecov()'
