# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  mariadb: 10.3

services:
  - mariadb

before_script:
  - sudo mariadb -e 'create database nycflights;'
  - sudo mariadb -e 'CREATE USER IF NOT EXISTS travis@localhost; GRANT ALL ON *.* TO travis@localhost; FLUSH PRIVILEGES;'

r:
  - oldrel
  - release
  - devel
os:
- linux
- osx
matrix:
  exclude:
  - os: osx
    r: oldrel
  - os: osx
    r: devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && test $TRAVIS_OS_NAME = "linux" && Rscript -e 'covr::codecov()'
