# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
dist: trusty

addons:
  apt:
    packages:
    - libpq-dev

before_install:
  - sh postgres-docker.sh

r:
  - oldrel
  - release
  - devel
os:
- linux
- osx
matrix:
  exclude:
  - os: osx
    r: oldrel
  - os: osx
    r: devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && test $TRAVIS_OS_NAME = "linux" && Rscript -e 'covr::codecov()'
