# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  postgresql: 10
  apt:
    packages:
     - libpq-dev
     - libssh2-1-dev

before_install:
  - if [ $TRAVIS_OS_NAME = "linux" ]; then sh postgres-docker.sh; fi
  - if [ $TRAVIS_OS_NAME = "osx" ]; then sh postgres-travis-macos.sh; fi
  - if [ $TRAVIS_OS_NAME = "linux" ]; then sh mariadb-docker.sh; fi
  - if [ $TRAVIS_OS_NAME = "osx" ]; then sh mariadb-travis-macos.sh; fi

r:
  - oldrel
  - release
  - devel
os:
- linux
- osx
matrix:
  exclude:
  - os: osx
    r: oldrel
  - os: osx
    r: devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && test $TRAVIS_OS_NAME = "linux" && Rscript -e 'covr::codecov()'
